name: Build & Deploy
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 9

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependancies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Setup Github Account
        run: |
          git config user.email "nka.debug@gmail.com"
          git config user.name "nkadebug"

      - name: Select GH-Pages Branch
        run: |
          git pull
          git checkout "gh-pages" || git checkout -b "gh-pages" && git rm -rf . && git checkout master -- .gitignore

      - name: Push To GH-Pages
        run: |
          cp -r dist/easy-prep/* .
          git add .
          set +e
          if git status | grep 'new file\|modified'
          then
              set -e
              git commit -m "Auto Updated $(date)"
              git push origin gh-pages
          else
              set -e
              echo "No changes since last run"
          fi
          echo "finish"
